# Experiment Lecture 03: Pytorch Basics
Deep Learning, GIST RT5101-01, 2019, Spring, (Tue/Thurs 2:30~3:45)
***

## Syllabus
- This course is for students who do not have prior knowledge of deep learning. It covers basic math tools, artificial neural network, multilayered perceptrons, backpropagation, deep convolutional neural network. The algorithms are applied to linear regression and image classification.
- Textbook: Deep Learning Book by Ian Goodfellow, Yoshua Bengio and Aaron Courville

### Course Overview

|       Week      |                              Tuesday                             | Thursday                                                       | HW                                                            |
|:---------------:|:----------------------------------------------------------------:|----------------------------------------------------------------|---------------------------------------------------------------|
|   1 (3/5, 3/7)  |                          Course overview                         |              Python, numpy basic (google   colab)              |                     Python, numpy   basic                     |
|  2 (3/12, 3/14) |                    Deep Learning Applications                    |        Setting environment (Pycharm,   Anaconda, github)       |        Install pytorch in   own computer, first commit        |
| 3 (3/19, 3/21)  | Linear Algebra                                                   | **Pytorch basic, gradient, OOP**           | No homework                      |
|     4 (3/26)    |                Probability and Information Theory                | no class (Student Workshop, SIT) |                                                               |
|   5 (4/2, 4/4)  |                       Numerical Computation                      |         Linear  regression, XOR problem           | Logistic regression with a given  dataset |
|  6 (4/9, 4/11)  |                      Machine Learning Basics                     |                         Logistic regression,  matplotlib                   |    XOR visualization                 |
|        7        |                           Midterm exam                           |                                                                |                                                               |
| 8 (4/23, 4/25)  |                     Deep Feedforward Networks                    |                       Feedforward network                      |    Feedforward network with given   dataset, visualization    |
| 9 (4/30, 5/2)   |                       Term Project Proposal                      |                  Convolutional neural networks                 |                       MNIST competition                       |
|  10 (5/7, 5/9)  |                   Convolutional Neural Networks                  |   handling datasets with pandas   |                     Handling   own dataset                    |
| 11 (5/14, 5/16) |                     Recurrent neural networks                    |           Tips   (Tensorboard, tqdm, hyperparameter)           |                          Tensorboard                          |
| 12 (5/21, 5/23) | Signal processing with Convolutional Neural Networks |                 CIFAR   with googleNet, ResNet                 |                      CIFAR   competition                      |
| 13 (5/28, 5/30) |        Signal processing with CNN-RNN networks       |                           RNN,   LSTM                          |                    visualize   own network                    |
|     14 (6/4)    |                     Term Project Final Presentation                                          |          no class (national holiday (현충일, Memorial Day))                                                      |                                                               |

## Teaching Staff
- Professor: Kyoobin Lee (kyoobinlee@gist.ac.kr)
- Postdoc: Hogeon Seo (hogeonseo@gist.ac.kr)
- TA: Seunghyeok Back (shback@gist.ac.kr)
- TA: Seongju Lee (lsj2121@gist.ac.kr)


### References
- https://pytorch.org/tutorials/
- https://pytorch.org/docs/
- https://github.com/yunjey/pytorch-tutorial
- https://deepsense.ai/keras-or-pytorch/
- https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a
- https://github.com/drvinceknight/oop/blob/master/nbs/main.ipynb

# 1. Introduction to Pytorch
---
## 1.1 DL Framework comparison (Statistics)
---
### Searches in google over the past two years
![Interest](https://user-images.githubusercontent.com/28585836/54474878-f6a13900-482d-11e9-861f-4582e19e44e5.png)

TensorFlow = red, Keras = yellow, PyTorch = blue, Caffe = green


### Performance Comparison
![performance](https://user-images.githubusercontent.com/28585836/54474894-20f2f680-482e-11e9-94fe-c21f9e66161e.png)

### ML papers
![ML papers](https://user-images.githubusercontent.com/28585836/54474889-17698e80-482e-11e9-86e0-cdd64bc60f0f.png)

### Arxiv articles
![Arxiv](https://user-images.githubusercontent.com/28585836/54474887-10428080-482e-11e9-90fd-9d8d4a953356.png)


## 1.2 Why pytorch
--- 

|                     	|     Pytorch    	|      Tensorflow     	|
|---------------------	|:--------------:	|:-------------------:	|
| Based on            	|      Torch     	|    Theano, Keras    	|
| Developed by        	|    Facebook    	|        Google       	|
| Community           	|     Active     	|   Bigger community  	|
| Computational Graph 	|  Dynamic Graph 	|     Static Graph    	|
| Debugging           	| Pythonic, Easy 	|      Difficult      	|
| Visualization       	|     Vizdom     	|     Tensorboard     	|
| Usage               	|    Research    	| Research/Production 	|



![code](https://user-images.githubusercontent.com/28585836/54475066-6c0e0900-4830-11e9-96c3-be47a2266288.png)



![Intro](https://user-images.githubusercontent.com/28585836/54474979-213fc180-482f-11e9-8dea-bfae66bfbac1.png)

- Actually, things are changed since tensorflow-2.0 has been released
- TF 2.0: Default eager execution + Keras as central component
- Anyway, Pytorch is a good starting point for deep learning beginners










# 2. Pytorch Tensors
---

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

##2.1 Getting Started
---

Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized:



In [36]:
x = torch.empty(5, 3) #토치 텐서가 존재함
# a block of memory is allocated according to the shape, but uninitialized
print(type(x))
print(x)
# print(x.tolist())
# print(x[1,1].tolist())
print(x.item((1,1))) 
print(x.item()) # 내부 답만가져오는법 1 dimension만 가능함.

<class 'torch.Tensor'>
tensor([[1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39],
        [1.0745e-38, 1.0653e-38, 9.5510e-39],
        [1.0561e-38, 1.0194e-38, 1.1112e-38]])
1.0193899821561958e-38


TypeError: item() takes no arguments (1 given)

Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3) #0~1 사이의 값으로 텐서 값이 랜덤하게 배정됨
print(x)

tensor([[0.3617, 0.2653, 0.9282],
        [0.4612, 0.0561, 0.1619],
        [0.7160, 0.4047, 0.1032],
        [0.1190, 0.7686, 0.2190],
        [0.7940, 0.3530, 0.8038]])


Construct a matrix filled zeros and of dtype long:



In [6]:
import torch
x = torch.zeros(5, 3, dtype=torch.long) #long tensor는 소숫점 낮은 자리까지 사용가능
print(x)
print(x.type())


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.LongTensor


Torch defines eight CPU tensor types and eight GPU tensor types:

| Data type                | dtype                         | CPU tensor         | GPU tensor              |
|--------------------------|-------------------------------|--------------------|-------------------------|
| 32-bit floating point    | torch.float32 or torch.float  | torch.FloatTensor  | torch.cuda.FloatTensor  |
| 64-bit floating point    | torch.float64 or torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 16-bit floating point    | torch.float16 or torch.half   | torch.HalfTensor   | torch.cuda.HalfTensor   |
| 8-bit integer (unsigned) | torch.uint8                   | torch.ByteTensor   | torch.cuda.ByteTensor   |
| 8-bit integer (signed)   | torch.int8                    | torch.CharTensor   | torch.cuda.CharTensor   |
| 16-bit integer (signed)  | torch.int16 or torch.short    | torch.ShortTensor  | torch.cuda.ShortTensor  |
| 32-bit integer (signed)  | torch.int32 or torch.int      | torch.IntTensor    | torch.cuda.IntTensor    |
| 64-bit integer (signed)  | torch.int64 or torch.long     | torch.LongTensor   | torch.cuda.LongTensor   |




Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x.type())
print(x)

torch.FloatTensor
tensor([5.5000, 3.0000])


Get its size:



In [10]:
x = torch.rand(5,3)
print(x)
print(x.size())
print(x.shape) # an alias for .size()

#사이즈를 가져올 경우 예제
y = torch.rand(x.size())
print(y)


tensor([[0.2403, 0.9349, 0.5847],
        [0.2010, 0.4964, 0.4599],
        [0.3298, 0.7610, 0.0597],
        [0.3718, 0.6126, 0.8731],
        [0.3116, 0.4676, 0.4641]])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[0.6152, 0.8280, 0.6806],
        [0.3898, 0.7967, 0.8995],
        [0.8360, 0.0119, 0.2330],
        [0.1949, 0.8087, 0.6793],
        [0.6760, 0.2553, 0.1509]])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations ==> Tuple은 변경 불가능함.</p></div>


There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8008, 1.8669, 1.0891],
        [0.7108, 0.5898, 1.2889],
        [1.3247, 1.4517, 0.4555],
        [1.0868, 0.7802, 1.8514],
        [0.6391, 1.2573, 1.1260]])


Addition: syntax 2



In [13]:
print(torch.add(x, y))

tensor([[0.8008, 1.8669, 1.0891],
        [0.7108, 0.5898, 1.2889],
        [1.3247, 1.4517, 0.4555],
        [1.0868, 0.7802, 1.8514],
        [0.6391, 1.2573, 1.1260]])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)# output을 result에 집어 넣는다. 
print(result)

tensor([[0.8008, 1.8669, 1.0891],
        [0.7108, 0.5898, 1.2889],
        [1.3247, 1.4517, 0.4555],
        [1.0868, 0.7802, 1.8514],
        [0.6391, 1.2573, 1.1260]])


Addition: in-place



In [16]:
# adds x to y (torch.Tensor.add = torch.add)
y.add_(x)
print(y)

tensor([[0.8008, 1.8669, 1.0891],
        [0.7108, 0.5898, 1.2889],
        [1.3247, 1.4517, 0.4555],
        [1.0868, 0.7802, 1.8514],
        [0.6391, 1.2573, 1.1260]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [20]:
print(x)
print(x[:, 1]) #tensor의 값을 가져 오기 위해서는 [대괄호]를 사용해야함. 
print(x[1,1])
print(x[:,0:-1])

tensor([[0.2403, 0.9349, 0.5847],
        [0.2010, 0.4964, 0.4599],
        [0.3298, 0.7610, 0.0597],
        [0.3718, 0.6126, 0.8731],
        [0.3116, 0.4676, 0.4641]])
tensor([0.9349, 0.4964, 0.7610, 0.6126, 0.4676])
tensor(0.4964)
tensor([[0.2403, 0.9349],
        [0.2010, 0.4964],
        [0.3298, 0.7610],
        [0.3718, 0.6126],
        [0.3116, 0.4676]])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [29]:
#tensor 변형 방법
x = torch.randn(4, 4) 
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions, 8개당 dimension이 늘어남. 

print(x,'\n')
print(y,'\n')
print(z,'\n')

print(x.size(), y.size(), z.size())

tensor([[ 8.3145e-01, -2.5884e+00, -9.6298e-01,  1.0758e+00],
        [ 3.0230e-01, -4.2291e-01,  4.8693e-01,  8.5850e-01],
        [ 4.9980e-01,  2.3486e-03, -1.6347e-01,  1.1613e+00],
        [ 3.7266e-01, -6.8159e-01,  1.7478e+00,  1.5572e+00]]) 

tensor([ 8.3145e-01, -2.5884e+00, -9.6298e-01,  1.0758e+00,  3.0230e-01,
        -4.2291e-01,  4.8693e-01,  8.5850e-01,  4.9980e-01,  2.3486e-03,
        -1.6347e-01,  1.1613e+00,  3.7266e-01, -6.8159e-01,  1.7478e+00,
         1.5572e+00]) 

tensor([[ 8.3145e-01, -2.5884e+00, -9.6298e-01,  1.0758e+00,  3.0230e-01,
         -4.2291e-01,  4.8693e-01,  8.5850e-01],
        [ 4.9980e-01,  2.3486e-03, -1.6347e-01,  1.1613e+00,  3.7266e-01,
         -6.8159e-01,  1.7478e+00,  1.5572e+00]]) 

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


![hellwo](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [30]:
x = torch.randn(1)
print(x)
print(x.item()) # 내부 답만가져오는법
print(type(x.item()))
# print(x.tolist())
# print(x[1,1].tolist())

tensor([3.0092])
3.0091793537139893
<class 'float'>


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

## 2.2 NumPy Bridge
---

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array




In [38]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy() # change torch.Tensor to numpy.ndarray
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


See how the numpy array changed in value.



In [40]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # change numpy.ndarray to torch.Tensor
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## 2.3 CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [44]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    z = z.to("cpu", torch.double)    # ``.to`` can also change dtype together!    
    print(z)      
    print(x, y, z)
else:
    print('no cuda')

cuda
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39],
        [1.0745e-38, 1.0653e-38, 9.5510e-39],
        [1.0561e-38, 1.0194e-38, 1.1112e-38]], device='cuda:0') tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0') tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)



# 3. Autograd: Automatic Differentiation
---
Central to all neural networks in PyTorch is the ``autograd`` package.

The ``autograd`` package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.


-  If you set its attribute ``.requires_grad`` as ``True``, it starts to track all operations on it. 
- When you finish your computation you can call ``.backward()`` and have all the gradients computed automatically. 
- The gradient for this tensor will be accumulated into ``.grad`` attribute.

- To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.



In [46]:
import torch

Create a tensor and set ``requires_grad=True`` to track computation with it



In [47]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:



In [0]:
y = x + 2
print(y)

``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [0]:
print(y.grad_fn)

Do more operations on ``y``



In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.



In [0]:
out.backward()

Print gradients d(out)/dx




In [0]:
print(x.grad)

You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [0]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

- To prevent tracking history (and using memory), you can also wrap the code block in ``with torch.no_grad():``.
- This can be particularly helpful when evaluating a model because the model may have trainable parameters with ``requires_grad=True``, but for which we don't need the gradients.

In [0]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

**Read Later:**

Documentation of ``autograd`` and ``Function`` is at
https://pytorch.org/docs/autograd





# 4. Object Oriented Programming : Class and Object
---

![OOP](https://user-images.githubusercontent.com/28585836/54489742-c2438080-48f2-11e9-8302-d2bb67c70264.png)

- Python is an object-oriented programming language
- A class defines the blueprint, and consist of attributes and methods
- A class can be instantiated to create objects
- An object is an instance of a class 


### 4.1 Defining a class
---

In [0]:
class Student():
    """We can create a simple empty class.
    
    This is a set of rules that says what a student is.
    """

In [0]:
kim = Student() # creating an instance (instantiation)
print(kim)

In [0]:
hong = Student() # creating a different instance
print(hong)

### 4.2 Attributes
---

In [0]:
class Student():
  courses = ["Deep Learning", "Robotics", "Data Science"]
  age = 25
  gender = "Male"
  
kim = Student()

In [0]:
print(kim.courses)
print(kim.age)
print(kim.gender)

We can manuplate these attributes just like any other python variable

In [0]:
kim.courses.append("Algoritm")
print(kim.courses)

In [0]:
kim.age = 28
kim.gender ="Female"
print(kim.age)
print(kim.gender)

### 4.3 Methods
---

In [0]:
class Student():
  courses = ["Deep Learning", "Robotics", "Data Science"]
  age = 25
  gender = "Male"

  def have_a_birthday(self):
    """This method increments the age of our instance."""
    self.age += 1

In [0]:
kim = Student()
print(kim.age)
kim.have_a_birthday()
print(kim.age)

### 4.4 \__init__method
---


In [0]:
class Student():
  def __init__(self, courses, age, gender):
    '''
    to create objects with instances customized to a specific initial stated
    automatically called when this class is instantiated.
    '''
    self.courses = courses
    self.age = age
    self.gender = gender
  
  def have_a_birthday(self):
    """This method increments the age of our instance."""
    self.age += 1

In [0]:
hong = Student(['deep learning'], 27, 'Female')
print(hong.courses)
print(hong.age)
print(hong.gender)


### 4.5 Inheritance
---


In [0]:
class Biology_Student(Student):
    """
    The 'Student' is a parent class of 'Biology_student'
    'Biology_student' is a child class of 'Student'
    A child class inherits the attributes and methods of its parent's class
    """
    favourite_class = "Neuroscience"

In [0]:
lee = Biology_Student(['robotics'], 24, 'Male')
lee.courses, lee.age, lee.gender, lee.favourite_class

In [0]:
lee.have_a_birthday()
lee.age